setup.py: drop deprecated and no longer functional "setup.py test" command
If you try to use it for the last year, you get this fatal error:

```
/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running test
[...]
RuntimeError: Support for the test command was removed in Setuptools 72
```

All it did was allow you to do the same thing you could already do via
`pytest` except that in theory it permitted you to have setuptools
download and inject an egg of pytest into the local source tree before
launching pytest itself. By and large, nobody used it, instead using
pytest directly. None of diffoscope's own packaging utilized it either.

It also annoyed me in Gentoo packaging every time I built it:

```
 * QA Notice: setuptools warnings detected:
 *
 * 	Unknown distribution option: 'tests_require'
```

Signed-off-by: Eli Schwartz <eschwartz@gentoo.org>