Amend 7zip version test for older 7z versions that include "[64]" string. (Closes: #376)
Without the change `7z` test fails with assertion errors:

    FAILED tests/comparators/test_sevenz.py::test_metadata_diff - AssertionError

This happens because version guard did not work for my ancient `7z`:

    $ 7z | head -n2

    7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28

THe change attempts to skip `[64]` identifier. Tested on 7z 17.05 only.